main/accounts/urls.py
from django.urls import path
from .views import *


app_name = "accounts"
urlpatterns = [
    path('', index,name="index"),
    path('login/', user_login, name="user_login"),

    path('tum-kullanicilar/', all_user_list, name="all_user_list"),
    path('kullanici-ekle/', kuyumcu_kullanici_add, name="kuyumcu_kullanici_add"),
    path('kullanici-veri-ekle/<int:user_id>/', kullanici_veri_ekle, name="kullanici_veri_ekle"),

    path('kullanici-veri-duzenle/<int:veri_id>/', kullanici_veri_duzenle, name="kullanici_veri_duzenle"),
    path('kullanici-veri-sil/<int:veri_id>/', kullanici_veri_sil, name="kullanici_veri_sil"),
]

main/home/urls.py
from django.urls import path
from .views import *

app_name = "home"
urlpatterns = [
    path('', index,name="index"),
]

main/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('account/', include("accounts.urls")),

]

main/accounts/models.py
from django.db import models
from django.urls import reverse


class KuyumcuKullanicilar(models.Model):
    STATUS = [
        ('Altın verildi', 'Altın verildi'),
        ('Altın Alındı!', 'Altın Alındı!'),
        ('İşlem Yok', 'İşlem Yok'),
    ]
    user = models.ForeignKey('auth.User', verbose_name='Author',
                             related_name='kuyumcu_kullanicilar', on_delete=models.CASCADE)
    tip = models.CharField(max_length=100)
    cins = models.CharField(max_length=100)
    miktar = models.DecimalField(max_digits=10, decimal_places=2)
    milyem_per_cm = models.DecimalField(max_digits=10, decimal_places=2)
    birim = models.CharField(max_length=10)
    alt_toplam = models.DecimalField(max_digits=10, decimal_places=2)
    aciklama = models.TextField()
    adet = models.IntegerField()
    iscilik = models.DecimalField(max_digits=10, decimal_places=2)
    mm_per_cm = models.CharField(max_length=10)
    isc_toplam = models.DecimalField(max_digits=10, decimal_places=2)
    islem_tipi = models.CharField(default="Test", choices=STATUS, max_length=30)
    tarih = models.DateTimeField(
        verbose_name="Tarih")


    def __str__(self):
        return self.name

main/home/models.py
from django.db import models

# Create your models here.

main/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import KuyumcuKullanicilar


class KuyumcuKullanicilarYeniKullaniciForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name']
    
    def save(self, commit=True):
        user = super(KuyumcuKullanicilarYeniKullaniciForm, self).save(commit=False)
        if not user.username:
            user.username = (user.first_name + user.last_name).lower().replace(' ', '') + str(User.objects.count() + 1)
        if commit:
            user.save()
        return user


class KuyumcuKullanicilarForm(forms.ModelForm):
    tarih = forms.DateTimeField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        required=True
    )
    class Meta:
        model = KuyumcuKullanicilar
        fields = ['tip', 'cins', 'miktar', 'milyem_per_cm', 'birim', 'alt_toplam', 'aciklama', 'adet', 'iscilik', 'mm_per_cm', 'isc_toplam', 'islem_tipi', 'tarih']

main/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from .forms import *
from .models import *
from django.db.models import Q

def index(request):
    return render(request, 'accounts/index.html')

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home:index')
        else:
            return HttpResponse('Invalid login details.')
    return render(request, 'accounts/login.html')



def all_user_list(request):
    query = request.GET.get('q')
    if query:
        users = KuyumcuKullanicilar.objects.filter(
            Q(name__icontains=query) |
            Q(tip__icontains=query) |
            Q(cins__icontains=query) |
            Q(miktar__icontains=query) |
            Q(milyem_per_cm__icontains=query) |
            Q(birim__icontains=query) |
            Q(alt_toplam__icontains=query) |
            Q(aciklama__icontains=query) |
            Q(adet__icontains=query) |
            Q(iscilik__icontains=query) |
            Q(mm_per_cm__icontains=query) |
            Q(isc_toplam__icontains=query)
        )
    else:
        users = User.objects.all()

    return render(request, 'accounts/user_list.html', {'users': users})

def kuyumcu_kullanici_add(request):
    if request.method == 'POST':
        form = KuyumcuKullanicilarYeniKullaniciForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            return redirect('accounts:kullanici_veri_ekle', user_id=new_user.id)
    else:
        form = KuyumcuKullanicilarYeniKullaniciForm()
        users = User.objects.all()
    
    context = {
        'users': users,
        'form': form
    }
    return render(request, 'accounts/kullanici_add.html', context)


def kullanici_veri_ekle(request, user_id):
    user = get_object_or_404(User, id=user_id)
    if request.method == 'POST':
        form = KuyumcuKullanicilarForm(request.POST)
        if form.is_valid():
            kuyumcu_kullanici = form.save(commit=False)
            kuyumcu_kullanici.user = user
            kuyumcu_kullanici.save()
            return redirect('accounts:kullanici_veri_ekle', user_id=user_id)
    else:
        form = KuyumcuKullanicilarForm()
    return render(request, 'accounts/kullanici_veri_ekle.html', {'form': form, 'user': user})


def kullanici_veri_duzenle(request, veri_id):
    veri = get_object_or_404(KuyumcuKullanicilar, id=veri_id)
    if request.method == 'POST':
        form = KuyumcuKullanicilarForm(request.POST, instance=veri)
        if form.is_valid():
            form.save()
            return redirect('accounts:kullanici_veri_ekle', user_id=veri.user.id)
    else:
        form = KuyumcuKullanicilarForm(instance=veri)
    return render(request, 'accounts/kullanici_veri_duzenle.html', {'form': form, 'veri': veri})

def kullanici_veri_sil(request, veri_id):
    veri = get_object_or_404(KuyumcuKullanicilar, id=veri_id)
    user_id = veri.user.id
    veri.delete()
    return redirect('accounts:kullanici_veri_ekle', user_id=user_id)

main/home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'home/index.html')

main/templates/accounts/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ana Sayfa</title>
</head>
<body>
    <h1>Hoşgeldiniz</h1>
    <a href="{% url 'accounts:kuyumcu_kullanici_add' %}"><button>Kullanıcı Ekle</button></a>
    <a href="{% url 'accounts:all_user_list' %}"><button>Kullanıcıları Listele</button></a>
</body>
</html>

main/templates/accounts/kullanici_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kullanıcı Ekle</title>
</head>
<body>
    <h2>Yeni Kullanıcı Ekle</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Ekle</button>
    </form>
    <table border="1">
        <tr>
            <th>Name</th>
        </tr>
        {% for user in users %}
        <tr>
            <td><a href="{% url 'accounts:kullanici_veri_ekle' user.id %}">{{ user.first_name }} {{ user.last_name }}</a></td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

main/templates/accounts/kullanici_veri_duzenle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Veri Düzenle</title>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function() {
            $("#id_tarih").datepicker({
                dateFormat: "yy-mm-dd"
            });
        });
    </script>
</head>
<body>
    <h2>Veri Düzenle</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Kaydet</button>
    </form>
    <a href="{% url 'accounts:kullanici_veri_ekle' veri.user.id %}">Geri Dön</a>
</body>
</html>

main/templates/accounts/kullanici_veri_ekle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ user.first_name }} için Veri Ekle</title>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function() {
            $("#id_tarih").datepicker({
                dateFormat: "yy-mm-dd"
            });
        });
    </script>
</head>
<body>
    <h2>{{ user.first_name }} için Veri Ekle</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Kaydet</button>
    </form>

    <h3>Veri Filtrele</h3>
    <form method="get">
        {{ filter_form.as_p }}
        <button type="submit">Filtrele</button>
    </form>

    <h3>Mevcut Veriler</h3>
    <table border="1">
        <tr>
            <th>Tip</th>
            <th>Cins</th>
            <th>Miktar</th>
            <th>Milyem/cm</th>
            <th>Birim</th>
            <th>Alt Toplam</th>
            <th>Açıklama</th>
            <th>Adet</th>
            <th>İşçilik</th>
            <th>mm/cm</th>
            <th>İşç. Toplam</th>
            <th>İşlem Tipi</th>
            <th>Tarih</th>
            <th>Düzenle</th>
            <th>Sil</th>
        </tr>
        {% for veri in user.kuyumcu_kullanicilar.all %}
        <tr>
            <td>{{ veri.tip }}</td>
            <td>{{ veri.cins }}</td>
            <td>{{ veri.miktar }}</td>
            <td>{{ veri.milyem_per_cm }}</td>
            <td>{{ veri.birim }}</td>
            <td>{{ veri.alt_toplam }}</td>
            <td>{{ veri.aciklama }}</td>
            <td>{{ veri.adet }}</td>
            <td>{{ veri.iscilik }}</td>
            <td>{{ veri.mm_per_cm }}</td>
            <td>{{ veri.isc_toplam }}</td>
            <td>{{ veri.islem_tipi }}</td>
            <td>{{ veri.tarih|date:"M d, Y" }}</td>
            <td><a href="{% url 'accounts:kullanici_veri_duzenle' veri.id %}">Düzenle</a></td>
            <td><button type="button" onclick="openModal('{{ veri.id }}')">Sil</button></td>
        </tr>
        {% endfor %}
    </table>
    <a href="{% url 'accounts:all_user_list' %}">Geri Dön</a>

    <!-- Modal -->
    <div id="modal" style="display:none;">
        <div style="background-color:white; padding:20px; border:1px solid black;">
            <p>Bu veriyi silmek istediğinizden emin misiniz?</p>
            <a id="confirm-delete" href="">Evet</a>
            <button type="button" onclick="closeModal()">Hayır</button>
        </div>
    </div>

    <script>
        function openModal(veriId) {
            document.getElementById('confirm-delete').href = '{% url "accounts:kullanici_veri_sil" 0 %}'.replace('0', veriId);
            document.getElementById('modal').style.display = 'block';
        }

        function closeModal() {
            document.getElementById('modal').style.display = 'none';
        }
    </script>
</body>
</html>

main/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
        <br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        <br>
        <button type="submit">Login</button>
    </form>
</body>
</html>

main/templates/accounts/user_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tüm kullanıcılar</title>
</head>
<body>
    <h2>Tüm kullanıcılar</h2>
    <table border="1">
        <tr>
            <th>Name</th>
        </tr>
        {% for user in users %}
        <tr>
            <td><a href="{% url 'accounts:kullanici_veri_ekle' user.id %}">{{ user.first_name }} {{ user.last_name }}</a></td>
         
        </tr>
        {% endfor %}
    </table>
</body>
</html>

main/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h2>Welcome to the Home Page</h2>
    <p>You are logged in!</p>
</body>
</html>